---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "taiga.fullname" . }}-back
  labels: {{- include "taiga.labels" . | nindent 4 }}
spec:
  type: {{ .Values.back.service.type }}
  {{- if (or (eq .Values.back.service.type "LoadBalancer") (eq .Values.back.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.back.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{ if eq .Values.back.service.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.back.service.loadBalancerSourceRanges }}
  {{ end }}
  {{- if (and (eq .Values.back.service.type "LoadBalancer") (not (empty .Values.back.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.back.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: http-taiga-back
      port: {{ .Values.back.service.port }}
      targetPort: http-taiga-back
      {{- if (and (eq .Values.back.service.type "NodePort") (not (empty .Values.back.service.nodePorts.http)))}}
      nodePort: {{ .Values.back.service.nodePorts.http }}
      {{- end }}
  selector: {{- include "taiga.matchLabels" . | nindent 4 }}
