---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "taiga.fullname" . }}-front
  labels: {{- include "taiga.labels" . | nindent 4 }}
data:
  conf.json: |
    {
      "api": "/api/v1/",
      "eventsUrl": "ws://127.0.0.1:8080/events",
      "eventsMaxMissedHeartbeats": 5,
      "eventsHeartbeatIntervalTime": 60000,
      "eventsReconnectTryInterval": 10000,
      "debug": true,
      "debugInfo": false,
      "defaultLanguage": "en",
      "themes": ["taiga"],
      "defaultTheme": "taiga",
      "publicRegisterEnabled": true,
      "feedbackEnabled": true,
      "supportUrl": "https://tree.taiga.io/support/",
      "privacyPolicyUrl": null,
      "termsOfServiceUrl": null,
      "GDPRUrl": null,
      "maxUploadFileSize": null,
      "contribPlugins": [],
      "tribeHost": null,
      "importers": [],
      "gravatar": true,
      "rtlLanguages": ["fa"]
    }
